### ISSUE TITLE
BGM not playing

### ISSUE THREAD

**Issue by DASA1409** [requinDr/tsukihime-port#10]
I've been playing the game since yesterday using Chrome on my phone, the BGMs were playing just fine, now I just open the game and I can no longer listen the BGM.

I don't know If a specific action could trigger it but I doubt it because it's the whole game that now lacks of any of the 3 BGM soundtracks.

**Comment by polarnyne** [comment]
Same problem here. Yesterday I was reading until 2nd day, saved and closed the game. I opened it today and the game doesn't produce any audio.

**Comment by DASA1409** [comment]
> Same problem here. Yesterday I was reading until 2nd day, saved and closed the game. I opened it today and the game doesn't produce any audio.
> 
> Edit: By reading the roadmap, it looks like this is a known bug.

Just checked too, and it's in a high priority right now, so it's probably going to get fixed quickly

**Comment by requinDr** [comment]
We are working on it, thanks for the feedback!

**Comment by requinDr** [comment]
Just published an [update](https://github.com/requinDr/tsukihime-port/releases/tag/v0.1.1) @DASA1409 @polarnyne
Please try again and tell me if it's solved for you. The version number in the `i` in the top left of the title menu should be `v0.1.1`, if not try to do a ctrl + F5

**Comment by DASA1409** [comment]
> Just published an [update](https://github.com/requinDr/tsukihime-port/releases/tag/v0.1.1) @DASA1409 @polarnyne Please try again and tell me if it's solved for you. The version number in the `i` in the top left of the title menu should be `v0.1.1`, if not try to do a ctrl + F5

Already working for me, thanks! This project is amazing👍

**Comment by polarnyne** [comment]
It works now! I already tested in both, PC and Android. I had to erase the data in both devices and re-start the game in order to get the VN fixed. Also, I found some minor bugs in the BGM that I think are caused by the Fast-Forward, but these are quickly fixed by re-starting the game. If I find a way to replicate them I'll open a new issue.

Thanks for your amazing work! You guys are godlike.

**Comment by requinDr** [comment]
Thank you for taking the time to test and report!
