### ISSUE TITLE
Save File has developed a fault

### ISSUE THREAD

**Issue by Doc-4** [requinDr/tsukihime-port#16]
I've had an issue where the data for the game developed a bug at some unknown point where opening the endings tab on the title screen results in a blank interface and a soft-lock. Erasing the data removes the bug and importing it brings it back, this happens on different device and browser types, in this case chromium on android and heroic launcher's embedded chromium on linux. I've uploaded it so you can debug the issue.
[2023-10-03_02-03.thfull.zip](https://github.com/requinDr/tsukihime-port/files/12789150/2023-10-03_02-03.thfull.zip)

**Comment by requinDr** [comment]
Yes, we fixed this yesterday with 6d658b7b5eff6c55f264df9cd5405258c6f0ef6e (but you are actually the first to report it!)
We will publish the update in the coming days
