### ISSUE TITLE
 Progression stopper on subsequent routes

### ISSUE THREAD

**Issue by Doc-4** [requinDr/tsukihime-port#17]
After clearing a route, the new option to go to sleep instead of investigating the noise doesn't load the next scene. Game data at this point attached.
[2023-10-03_13-22.thfull.zip](https://github.com/requinDr/tsukihime-port/files/12795238/2023-10-03_13-22.thfull.zip)

**Comment by requinDr** [comment]
Thank you for the report. The bug is fixed and said fix will be published in the coming days update

**Comment by Doc-4** [comment]
Thanks for the heads up. I don't want to create any more redundant issues, is the bug with the credits displaying formatting as plain text and then going to a blank blue screen if the scene isn't skipped also fixed?

**Comment by loicfrance** [comment]
Can you test it on https://holofield.fr/tsukidev ? There was some error with the credits, but I don't remember anything about formatted text displayed as plain text

**Comment by Doc-4** [comment]
I'm referring to this kind of issue
![Screenshot_20231003_163043](https://github.com/requinDr/tsukihime-port/assets/60247583/d428eff7-5563-43f0-aa23-fcbf995a15f4)

**Comment by loicfrance** [comment]
Oh, I do have the same issue. I was not expecting this kind of issue in the middle of the credits. Thanks for pointing it out. I should be able to fix it soon.

**Comment by Doc-4** [comment]
Nice. I used a save made on the dev version to test beyond the branch where you go to sleep, there's another progression stopper in both dev and normal where you choose to or not to mention the missing classmate. 

I'm going to assume going forward that the dev page is mostly up to date with the git repo at any given time? If so, I'll report bugs only if they also exist in that build

**Comment by loicfrance** [comment]
Yes, you can consider that the dev page is up to date. Note that it _might_ be a few commits behind head.
I'll take a look at the issue you are reporting on the progression stopper.

**Comment by requinDr** [comment]
The update has been published
