### ISSUE TITLE
Sound Bug when reaching Ciel's Lessons

### ISSUE THREAD

**Issue by AgusMarotte** [requinDr/tsukihime-port#2]
When reaching Ciel's Lessons, after it sends you back to the Title Screen you can press Continue, it will try to send you to the end of the Ciel Lesson and the OST will start playing in the Title Screen, you can hit Continue multiple times to have the OST play multiple times simultaneously

**Comment by requinDr** [comment]
Thanks for the feedback, we'll look into it

**Comment by jhallbachner** [comment]
Experiencing this pretty frequently early on. It seems to be specifically tied to loading a save game on a line where music is playing; the track that starts alongside the load will continue to play (at a reduced volume) even after returning to the title, and you can cause any number of copies to simultaneously loop by repeating this. If I load on a silent screen I don't get this issue.

**Comment by requinDr** [comment]
Fixed with v0.1.1
