### ISSUE TITLE
Kohaku route freeze

### ISSUE THREAD

**Issue by u3570964** [requinDr/tsukihime-port#21]
At s416, after the text:

"Stretching out my arms, I let out a deep breath.
―― I should just stop thinking about Akiha.
I should go to sleep and wait until tomorrow-----"

The white screen animation plays, then the game freezes.

Exported save file:
[2023-10-07_19-24.zip](https://github.com/requinDr/tsukihime-port/files/12837921/2023-10-07_19-24.zip)

**Comment by loicfrance** [comment]
Thanks for the report.
I understand what causes this issue, I'll fix it when I have time.
