### ISSUE TITLE
Roadmap towards 1.0?

### ISSUE THREAD

**Issue by R1kaB3rN** [requinDr/tsukihime-port#3]
First of all, thanks for this awesome port of Tsukihime! 

As the title suggests, I think it would be helpful to have a roadmap to guide contributors towards some needed or missing features of this port in addition to the [contributing guidelines](https://github.com/requinDr/tsukihime-port/blob/8fe8fd2b2b43d6f5cb3aa8ad3260254a33978fc1/CONTRIBUTING.md)

**Comment by requinDr** [comment]
Hi, you're right, we should publish a roadmap if anyone wants to help.
I wrote it here just now [https://github.com/requinDr/tsukihime-port/wiki](https://github.com/requinDr/tsukihime-port/wiki)

It's quite simple at the moment and will need more details. I'll add the link to the README later

**Comment by requinDr** [comment]
1.0 will be for when users stops reporting blocking/major issues, so it's not a clear goal. Features and changes will probably be made on the way to 1.0 and after
