### ISSUE TITLE
Consider merging the JP/ENG script

### ISSUE THREAD

**Issue by R1kaB3rN** [requinDr/tsukihime-port#4]
Assuming contributions to the English script are welcome, it isn't easy to make changes given how the scripts are currently organized. 

Since ENG and JP scripts are located in separate directories, translators/editors need to refer to both files, have them open, and match the equivalent lines. [Tsukihimates has a better model for this](https://github.com/Tsukihimates/Tsukihime-Translation/tree/main/script), where they're merged and the scenes are organized by heroine/days, so it's trivial to compare the TL to its source and make appropriate changes.

**Comment by requinDr** [comment]
Contributions to fix typos are welcome, but it's not intended as a translation tool.  
In fact, we keep the scripts close to the original so that we can add more existing translations in the future.  

That's why we don't plan on merging the files at the moment
