### ISSUE TITLE
Stuck before the end of s46

### ISSUE THREAD

**Issue by tlkoMagisto** [requinDr/tsukihime-port#5]
I get stuck here if text display speed is set to Instant:

1 / Reactionary Impulse I
1st day | October 21 (Thur.)

The little cursor disappears and it becomes impossible to proceed when I get to "Awooooo. [break] Awooooo.", it never gets to the third longer one.

I tried getting through it many times but it only worked after I set it to Medium and then I tried it again with Instant and it didn't work then I set it to Fast and that worked as well.

**Comment by requinDr** [comment]
Fixed with the next update, thanks for the detailed report!

**Comment by requinDr** [comment]
The update has been published
